import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/AuthContext/AuthContextProvider";
import Navbar from "../components/Navbar";
import QueryClients from "../../libs/queryClients/QueryClients";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BSIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:px-16 px-5`}
      >
        <QueryClients>
        <AuthContextProvider>
          <Navbar></Navbar>
          {children}
        </AuthContextProvider>
        </QueryClients>
      </body>
    </html>
  );
}
